### PR TITLE
make the sidebar more grey

### PR DESCRIPTION
**Pull request by tischrei**

### CODE REVIEW

**Review by gtema — COMMENTED** [review]
Maybe even 70? 80 is very close to original

**Comment by tischrei** [comment]
Sure, possible. My idea was to have a separation to the "Page Contents" navbar. Otherwise it looks the same and we can use 60 as well. I already tried it and felt comfortable with 80.

**Comment by gtema** [comment]
I think that we should try to check on some repo with long navbar.

**Comment by SebastianGode** [comment]
recheck

**Pull request closed without merging**
