### PR TITLE
Changed a colours to brand default

### PR DESCRIPTION
**Pull request by SebastianGode**

### CODE REVIEW

**Comment by gtema** [comment]
How this relates to #38?

**Comment by SebastianGode** [comment]
> How this relates to #38?

This changes the links inside the documentation text to the Telekom blue and slightly darker if you hover over it.
#38 just changes the sidebar to hover magenta.

Separate PRs because opinions may differ on those two things.

**Comment by gtema** [comment]
ah ok, I didn't properly recognized where the changes were. I actually explicitly chosen this one as a slightly lighter blue harmonized for me better with other colors that we use (not standalone link, but close to other colors

**Comment by SebastianGode** [comment]
Okay, yeah no worries.
The blues nearly don't differ. Just though I will open the PR for the official stuff. If you don't like it I don't mind not merging it as for me it makes no difference.

**Comment by gtema** [comment]
https://swift.eco.tsi-dev.otc-service.com/v1/AUTH_73733c21728443609ee0b47f64b5ce0b/zuul_logs/2ba/40/57e5d3d6dfd5c537d0d8675645a7e35e03d4cfb4/check/otc-tox-docs/2bab020/docs/demo/index.html#configuration-addition-and-deprecation-notices is a place where it is pretty dark with other colors. And also page options require some visual "light" feeling

**Comment by SebastianGode** [comment]
Yeah just leave it lighter then.

**Review by tischrei — APPROVED** [review]

**Pull request closed without merging**
